environment:
    php: "/usr/bin/php"
wiki:
    # BlueSpice Neo is a farm. But paralle-runjobs-service has no setting for neo. Therefore we hardode it.
    # This must be changed in a unified image for classic/neo
    type: "farm"
    path: "/app/bluespice/w"
database:
    dbserver: "###DB_HOST###"
    dbport: 3306
    dbname: "###DB_NAME###"
    dbuser: "###DB_USER###"
    dbpassword: "###DB_PASS###"
    dbprefix: "###DB_PREFIX###"
runjobs:
    cooldown: 5
farm:
    include-instances: []
    exclude-instances: []